# Generated by Django 4.1.5 on 2023-01-18 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('kind', models.CharField(default='', max_length=50)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_site/%Y%m%d')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea_star', models.BooleanField(default=False)),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tool', to='idea_site.tool')),
            ],
        ),
    ]
