# Generated by Django 4.1.5 on 2023-01-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Tool', to='idea_site.tool'),
        ),
    ]
