# Generated by Django 4.1.5 on 2023-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='https://picsum.photos/300/400', max_length=100)),
                ('title', models.CharField(default='', max_length=24)),
                ('director', models.CharField(default='', max_length=24)),
                ('actor', models.CharField(default='', max_length=24)),
                ('genre', models.CharField(default='', max_length=12)),
                ('stars', models.FloatField(default=0)),
                ('createDate', models.DateField(default='', max_length=12)),
                ('runtime', models.IntegerField(default=0)),
                ('explain', models.CharField(default='대통령은 국무회의의 의장이 되고, 국무총리는 부의장이 된다. 국회는 국민의 보통·평등·직접·비밀선거에 의하여 선출된 국회의원으로 구성한다. 헌법개정은 국회재적의원 과반수 또는 대통령의 발의로 제안된다.', max_length=200)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
