# Generated by Django 4.1.5 on 2023-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='actor',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='reviews',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reviews',
            name='director',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='reviews',
            name='genre',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='reviews',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='', max_length=24),
        ),
    ]
