# Generated by Django 4.1.5 on 2023-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createDate',
            field=models.CharField(default='', max_length=12),
        ),
    ]
